### ISSUE TITLE
Adding a profile shouldn't reset the form

### ISSUE THREAD

**Issue by Jvargasw** [sjara/jaraviewer#31]

**Comment by nicolehsieh** [comment]
When user click on the save button(checkbox) and submit the form to add profile, it refreshes the page. So everything that was selected is now cleared. User can click on the most recent saved profile again to select the fields again.

If we don't clear the data. Every time someone come to our site, the last saved profile will be preselected. 
I think it would be best to clear the data so that other people wouldn't have to manually hit reset every time they visit the site.
